### ISSUE TITLE
Handle failures in document transformations

### ISSUE THREAD

**Issue by vegardb** [metno/met_moai#2]
Trying to convert an invalid mmd document into iso causes internal server error - also in ListRecords.

Find some way to handle document errors in ListRecords, so the user at least may get a list of all valid records.

**Comment by steingod** [comment]
This is not only for conversion to ISO, but also to GCMD DIF. As it sits now, my gut feeling is that we should not provide any output for these documents. However, I see that conversion may fail after a document has been published (for various reasons) and then it certainly should provide an appropriate message. I think the quick fix should be to leave such documents out of the stream, in the longer perspective we should discuss alternatives.
